# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('project_type', models.CharField(choices=[('R&D', 'Research & Development'), ('WA', 'Web Application'), ('DeOP', 'Devops'), ('AI', 'Artificial Intelligence'), ('DM', 'Data Mining')], default='R&D', max_length=5)),
                ('team_assigned', models.CharField(max_length=100)),
                ('completion_status', models.IntegerField()),
            ],
        ),
    ]
